
about :

  name : 'wgraphextra'
  description : 'Collection of abstract data structures and algorithms to process graphs. The module does not bound to any specific format of a graph, so providing adapters toy may use it with anyone. It implements depth-first search, breadth-first search, extracting strongly connected components, topological sort, shortest path search, and others.'
  version : '0.4.0'
  enabled : 1
  interpreters :
  - njs >= 10.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools
  - graph
  license : MIT
  author : 'Kostiantyn Wandalen <wanalen@01.school>'
  contributors :
  - 'Kostiantyn Wandalen <wanalen@01.school>'
  npm.name : 'wgraphextra'
  npm.scripts :
    test : 'wtest .run proto/** rapidity:-1'
    docgen : 'wdocgen .build proto'

path :

  repository : git+https:///github.com/Wandalen/wgraphextra.git
  origins :
   - git+https:///github.com/Wandalen/wgraphextra.git
   - npm:///wgraphextra
  bugtracker : https:///github.com/Wandalen/wgraphextra/issues

step :

  proto.export :
    inherit : module.export
    export : path::export
    tar : 0
    criterion :
      content : 'proto'

  doc.export :
    inherit : module.export
    export : path::doc
    tar : 0
    criterion :
      content : 'doc'

  npm.export :
    inherit : module.export
    export : out.npm
    tar : 0
    criterion :
      content : 'npm'

  npm.publish :
    shell : npm publish

build :

  proto.export :
    criterion :
      content : 'proto'
      export : 1
    steps :
      # - build::debug.raw
      - step::proto.export

  doc.export :
    criterion :
      content : 'doc'
      export : 1
    steps :
      # - build::debug.raw
      - step::doc.export

  npm.export :
    criterion :
      content : 'npm'
      export : 1
    steps :
      # - build::debug.raw
      # - step::npm.export
      - step::npm.publish

  export :

    criterion :
      default : 1
      export : 1
    steps :
      # - build::npm
      - build::proto.export
      # - build::doc.export
